### ISSUE TITLE
Proposal: throw away diag.rs module and use proc-macro-error crate

### ISSUE THREAD

**Issue by CreepySkeleton** [auto-impl-rs/auto_impl#58]
Hey there!

I see you put significant effort into error reporting in your crate. It so happened that I'm very interested in the situation around error reporting in proc-macros and I made [a crate](https://crates.io/crates/proc-macro-error) just for it. 

It turns out that most of the code in your `diag.rs` module is very very similar to the code in my crate (thread local storage of errors, emitting effectively puts the new error into this storage). Thus I would like to help you move from your DIY solution to my crate, I believe code should be reused as much as possible. 

What do you think? Just say yes and I'll make a PR in, say, 4 days (I'm kind of busy right now).

P.S. The latest published version doesn't support "note" messages quite yet but I'm on the verge of new release that will support them quite reasonably.

**Comment by LukasKalbertodt** [comment]
Hi there! 

Thanks for reaching out to us. While writing `diag.rs` I certainly wished that there was a nice proc macro error reporting library. So I'm very tempted to replace it with a library.

However, I'm not quite sure about `proc-macro-error`. Reading over the documentation, it seems a bit too much magic to me. Especially the `#[proc_macro_error]` attribute and what exactly it does to the main function is not clear to me. But maybe it's indeed a good way to do error reporting in proc macros and I just don't understand yet. I would have to try it or see it in action to really be able to judge.

If you want, you can prepare a PR under the condition that I might still say "no" to it. Of course I'm not the only one deciding things for `auto-impl`. And we should probably wait for your new release so that `auto-impl` does not loose functionality (notes). But I can also totally understand if you don't want to create a PR that might get rejected.

**Comment by CreepySkeleton** [comment]
There's no magic involved, actually. `#[proc_macro_error]` just helps you to build up right [`entry_point` invocation](https://docs.rs/proc-macro-error/0.3.4/proc_macro_error/fn.entry_point.html) while keeping indentation level flat. What exactly it does:

- It makes a closure of your whole top-level function, wrapping it with [`AssertUnwindSafe`](https://doc.rust-lang.org/std/panic/struct.AssertUnwindSafe.html) if needed or requested (for example, prior to Rust 1.37 `proc_macro::TokenStream` didn't implement `UnwindSafe` so this wrapper is necessary). Then it just gives this closure over to `entry_point`, the real work gets done there.
- First, `entry_point` executes your code, catching all the panics via `catch_unwind`. Then it clears the `thread_local` storage, resumes panic if it's not especial `AbortNow`. Then, if storage is empty - it just returns your closure's result, if not - makes a sequence of `compile_error!` invocations and returns it instead. Basically, that's all.

As you see, there's no magic in it. Moreover, if you decide to implement such global storage at yourself you'll simply end up reimplementing 80% of my crate and there's no guarantee you won't miss something. For example, global storage **MUST** be cleared (you already know *what* might happen if you don't do that :smile:), even in case of panic, so you would have to use `catch_unwind` too, which brings all the headache of `AssertUnwingSafe`. 

> If you want, you can prepare a PR under the condition that I might still say "no" to it.

This is just sensible, I would be very surprised otherwise. In fact, I was just checking if it's still maintained :)

**Comment by LukasKalbertodt** [comment]
Closed in #60
